// Generated by CoffeeScript 1.6.3
(function() {
  var key, ursa;

  ursa = require('ursa');

  key = require('./key');

  exports.make = function(info) {
    var privKey, sig;
    privKey = key.createPrivate();
    sig = privKey.hashAndSign('sha512', info);
    return [sig, privKey.toPublicPem()];
  };

  exports.verify = function(candidate, commitment, decommitment) {
    var pubKey;
    pubKey = ursa.createPublicKey(decommitment);
    return pubKey.hashAndVerify('sha512', candidate, commitment);
  };

}).call(this);
